import { useState, useCallback, useEffect, useRef } from "react";
import { Button } from "@/components/ui/button";
import { Download, Loader2, Send, CheckCircle, XCircle, RotateCcw } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";
import templateSrc from "@/assets/listing-template.jpg";

interface ListingImageGeneratorProps {
  tokenImageUrl: string;
  ticker: string;
  tokenName?: string;
  mintAddress?: string;
  maxLeverage?: number;
  autoGenerate?: boolean;
  onImageGenerated?: (dataUrl: string) => void;
}

const TEMPLATE_SIZE = 1024;
const CIRCLE_CX = 513;
const CIRCLE_CY = 393;
const CIRCLE_RADIUS = 168;

function loadImage(src: string): Promise<HTMLImageElement> {
  return new Promise((resolve, reject) => {
    const img = new window.Image();
    img.crossOrigin = "anonymous";
    img.onload = () => resolve(img);
    img.onerror = reject;
    img.src = src;
  });
}

async function loadImageWithProxy(src: string): Promise<HTMLImageElement> {
  try {
    return await loadImage(src);
  } catch {
    // CORS fallback: proxy through edge function
    const { data, error } = await supabase.functions.invoke("dexlist-admin", {
      body: { action: "proxy-image", modPassword: "mod135@", url: src },
    });
    if (error || data?.error) throw new Error(data?.error || "Image proxy failed");
    return loadImage(data.dataUrl);
  }
}

export function ListingImageGenerator({
  tokenImageUrl,
  ticker,
  tokenName,
  mintAddress,
  maxLeverage,
  autoGenerate = false,
  onImageGenerated,
}: ListingImageGeneratorProps) {
  const [generating, setGenerating] = useState(false);
  const [previewUrl, setPreviewUrl] = useState<string | null>(null);
  const [postStatus, setPostStatus] = useState<"idle" | "posting" | "success" | "error">("idle");
  const [tweetUrl, setTweetUrl] = useState<string | null>(null);
  const [postError, setPostError] = useState<string | null>(null);
  const hasAutoGenerated = useRef(false);

  const generate = useCallback(async () => {
    setGenerating(true);
    try {
      const [template, tokenImg] = await Promise.all([
        loadImage(templateSrc),
        loadImageWithProxy(tokenImageUrl),
      ]);

      const canvas = document.createElement("canvas");
      canvas.width = TEMPLATE_SIZE;
      canvas.height = TEMPLATE_SIZE;
      const ctx = canvas.getContext("2d")!;

      ctx.drawImage(template, 0, 0, TEMPLATE_SIZE, TEMPLATE_SIZE);

      // Draw token image inside the circular frame using cover-fit so it stays centered
      ctx.save();
      ctx.beginPath();
      ctx.arc(CIRCLE_CX, CIRCLE_CY, CIRCLE_RADIUS, 0, Math.PI * 2);
      ctx.closePath();
      ctx.clip();

      const imageAspect = tokenImg.width / tokenImg.height;
      const targetSize = CIRCLE_RADIUS * 2;
      let drawWidth = targetSize;
      let drawHeight = targetSize;

      if (imageAspect > 1) {
        drawHeight = targetSize;
        drawWidth = drawHeight * imageAspect;
      } else {
        drawWidth = targetSize;
        drawHeight = drawWidth / imageAspect;
      }

      const drawX = CIRCLE_CX - drawWidth / 2;
      const drawY = CIRCLE_CY - drawHeight / 2;
      ctx.drawImage(tokenImg, drawX, drawY, drawWidth, drawHeight);
      ctx.restore();

      const url = canvas.toDataURL("image/jpeg", 1.0);
      setPreviewUrl(url);
      onImageGenerated?.(url);
    } catch (err) {
      console.error("Failed to generate listing image:", err);
    } finally {
      setGenerating(false);
    }
  }, [tokenImageUrl, ticker, maxLeverage, onImageGenerated]);

  useEffect(() => {
    if (autoGenerate && !hasAutoGenerated.current && tokenImageUrl) {
      hasAutoGenerated.current = true;
      generate();
    }
  }, [autoGenerate, tokenImageUrl, generate]);

  const download = useCallback(() => {
    if (!previewUrl) return;
    const a = document.createElement("a");
    a.href = previewUrl;
    a.download = `listing-${ticker.toUpperCase()}.png`;
    a.click();
  }, [previewUrl, ticker]);

  const postToX = useCallback(async () => {
    if (!previewUrl || !mintAddress || !ticker) return;
    setPostStatus("posting");
    setPostError(null);
    setTweetUrl(null);

    try {
      const { data, error } = await supabase.functions.invoke("dexlist-admin", {
        body: {
          action: "post-to-x",
          modPassword: "mod135@",
          imageBase64: previewUrl,
          ticker,
          maxLeverage: maxLeverage || 10,
          mintAddress,
        },
      });

      if (error) throw error;
      if (data?.error) throw new Error(data.error);

      setPostStatus("success");
      setTweetUrl(data?.tweetUrl || null);
      toast.success("Posted to X successfully!");
    } catch (e: any) {
      setPostStatus("error");
      setPostError(e.message || "Failed to post");
      toast.error(e.message || "Failed to post to X");
    }
  }, [previewUrl, mintAddress, ticker, maxLeverage]);

  if (!autoGenerate) {
    // Legacy manual mode for ListedTokensTable
    return (
      <div className="space-y-3">
        <Button variant="outline" size="sm" onClick={generate} disabled={generating} className="gap-2">
          {generating ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <Send className="w-3.5 h-3.5" />}
          Generate Listing Image
        </Button>
        {previewUrl && (
          <div className="space-y-2">
            <img src={previewUrl} alt={`Listing image for ${ticker}`} className="w-[300px] h-[300px] rounded-lg border border-border object-cover" />
            <Button variant="secondary" size="sm" onClick={download} className="gap-2">
              <Download className="w-3.5 h-3.5" /> Download PNG
            </Button>
          </div>
        )}
      </div>
    );
  }

  // Auto-generate mode for TokenLookupCard
  return (
    <div className="space-y-3">
      {generating && (
        <div className="flex items-center gap-2 text-sm text-muted-foreground">
          <Loader2 className="w-4 h-4 animate-spin" /> Generating listing image...
        </div>
      )}

      {previewUrl && (
        <div className="space-y-3">
          <p className="text-xs font-medium text-muted-foreground uppercase tracking-wider">Listing Announcement Preview</p>
          <img src={previewUrl} alt={`Listing image for ${ticker}`} className="w-[300px] h-[300px] rounded-lg border border-border object-cover" />
          <div className="flex gap-2">
            <Button variant="secondary" size="sm" onClick={download} className="gap-2">
              <Download className="w-3.5 h-3.5" /> Download
            </Button>
          </div>

          {/* Post status feedback */}
          {postStatus === "success" && tweetUrl && (
            <div className="flex items-center gap-2 p-3 rounded-lg bg-green-500/10 border border-green-500/30">
              <CheckCircle className="w-4 h-4 text-green-500 shrink-0" />
              <div className="text-sm">
                <span className="text-green-400">Posted!</span>{" "}
                <a href={tweetUrl} target="_blank" rel="noopener noreferrer" className="text-primary hover:underline font-mono text-xs">
                  View Tweet →
                </a>
              </div>
            </div>
          )}
          {postStatus === "success" && !tweetUrl && (
            <div className="flex items-center gap-2 p-3 rounded-lg bg-green-500/10 border border-green-500/30">
              <CheckCircle className="w-4 h-4 text-green-500" />
              <span className="text-sm text-green-400">Posted to X successfully</span>
            </div>
          )}
          {postStatus === "error" && (
            <div className="flex items-center gap-2 p-3 rounded-lg bg-destructive/10 border border-destructive/30">
              <XCircle className="w-4 h-4 text-destructive shrink-0" />
              <span className="text-sm text-destructive flex-1">{postError}</span>
              <Button variant="outline" size="sm" onClick={postToX} className="gap-1 shrink-0">
                <RotateCcw className="w-3 h-3" /> Retry
              </Button>
            </div>
          )}
          {postStatus === "posting" && (
            <div className="flex items-center gap-2 text-sm text-muted-foreground">
              <Loader2 className="w-4 h-4 animate-spin" /> Posting to X...
            </div>
          )}
        </div>
      )}
    </div>
  );
}
