import { useState } from "react";
import { motion } from "framer-motion";
import { Flame, Shield, DollarSign, Users, CheckCircle2, XCircle, ArrowRight, Zap, TrendingUp, Lock, MessageSquare, BadgeCheck, Search, ExternalLink } from "lucide-react";
import { LaunchpadLayout } from "@/components/layout/LaunchpadLayout";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";
import { BRAND } from "@/config/branding";

const ease = [0.16, 1, 0.3, 1] as [number, number, number, number];

// Mock data for demo
const MOCK_TOKENIZED_TWEETS = [
  {
    id: "1",
    tweetUrl: "https://x.com/elonmusk/status/123456",
    author: "@elonmusk",
    authorImg: null,
    content: "The future of money is digital. Banks are running on software from the 80s.",
    tokenCA: "7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgAsU",
    totalCommenters: 847,
    eligibleCommenters: 312,
    totalFeesEarned: 24.7,
    createdAt: "2h ago",
    status: "live",
  },
  {
    id: "2",
    tweetUrl: "https://x.com/VitalikButerin/status/789012",
    author: "@VitalikButerin",
    authorImg: null,
    content: "Ethereum's roadmap is about making L1 simpler and L2s more powerful.",
    tokenCA: "9pKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgBsV",
    totalCommenters: 1203,
    eligibleCommenters: 489,
    totalFeesEarned: 18.3,
    createdAt: "5h ago",
    status: "live",
  },
  {
    id: "3",
    tweetUrl: "https://x.com/caboredapes/status/345678",
    author: "@CryptoWhale",
    authorImg: null,
    content: "Just bought 500 $SOL at $180. This is the bottom. Screenshot this.",
    tokenCA: null,
    totalCommenters: 234,
    eligibleCommenters: 0,
    totalFeesEarned: 0,
    createdAt: "12m ago",
    status: "pending",
  },
];

const FEATURES = [
  {
    icon: Flame,
    title: "Tweet Goes Viral → Token Gets Born",
    desc: "Any tweet can be turned into a tradeable token. The more engagement, the more valuable it becomes. Every comment is a ticket to earn.",
  },
  {
    icon: DollarSign,
    title: "25% to Tweet Owner",
    desc: "The original tweet author receives 25% of all swap fees generated by their tokenized tweet. Create viral content, get paid forever.",
  },
  {
    icon: Users,
    title: "25% Split Among Commenters",
    desc: "Every verified commenter splits 25% of swap fees proportionally. One comment per tweet — first come, first served. Quality over quantity.",
  },
  {
    icon: Shield,
    title: "Blue Check Required",
    desc: "Only verified X accounts (blue checkmark) can participate. No bots, no spam, no shadowbanned accounts. Real humans, real rewards.",
  },
];

const RULES = [
  { icon: BadgeCheck, text: "Must have X Blue verification (checkmark)", ok: true },
  { icon: Shield, text: "Account must NOT be shadowbanned", ok: true },
  { icon: MessageSquare, text: "Only 1 comment per tweet counts", ok: true },
  { icon: DollarSign, text: "25% fees → tweet owner", ok: true },
  { icon: Users, text: "25% fees → split among all eligible commenters", ok: true },
  { icon: Zap, text: "2% swap fee on every trade", ok: true },
  { icon: XCircle, text: "No duplicate comments from same account", ok: false },
  { icon: XCircle, text: "No shadowbanned or suspended accounts", ok: false },
  { icon: XCircle, text: "No bot accounts or automated replies", ok: false },
];

const HOW_IT_WORKS = [
  { step: "01", title: "Tweet Goes Viral", desc: "A tweet gains massive traction on X. Anyone can submit it to Meteorite." },
  { step: "02", title: "Commenters Pile In", desc: "Verified users comment under the tweet. Each valid comment = 1 claim ticket." },
  { step: "03", title: "Tweet Gets Tokenized", desc: "The tweet is minted as a tradeable token on Solana via Saturn." },
  { step: "04", title: "Saturn Replies", desc: `Our main account replies: "This tweet is now tokenized. All commenters are eligible to claim from swap fees."` },
  { step: "05", title: "Trade & Earn", desc: "Every swap generates fees. 25% to the author, 25% split among commenters. Forever." },
];

export default function MeteoritePage() {
  const [tweetUrl, setTweetUrl] = useState("");

  return (
    <LaunchpadLayout>
      <div className="min-h-screen pb-24">
        {/* Hero */}
        <section className="relative overflow-hidden pt-16 pb-20 px-4">
          <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_top,hsl(var(--primary)/0.08)_0%,transparent_60%)]" />
          <div className="max-w-4xl mx-auto relative z-10">
            <motion.div
              initial={{ opacity: 0, y: 18, filter: "blur(4px)" }}
              animate={{ opacity: 1, y: 0, filter: "blur(0px)" }}
              transition={{ duration: 0.7, ease }}
              className="text-center"
            >
              <Badge variant="outline" className="mb-6 border-orange-500/40 text-orange-400 bg-orange-500/5 px-3 py-1 text-xs font-semibold tracking-wide uppercase">
                <Flame className="w-3 h-3 mr-1.5" />
                Meteorite Mode
              </Badge>
              <h1 className="text-4xl sm:text-5xl lg:text-6xl font-black text-foreground leading-[0.95] tracking-tight mb-6">
                Every Tweet is a<br />
                <span className="text-transparent bg-clip-text bg-gradient-to-r from-orange-400 via-amber-400 to-yellow-300">
                  Cash Machine
                </span>
              </h1>
              <p className="text-muted-foreground text-lg sm:text-xl max-w-2xl mx-auto leading-relaxed mb-10" style={{ textWrap: "balance" }}>
                Tweets get tokenized. Tweet owners earn 25%. Commenters split 25%. 
                Every trade generates fees that flow to creators and their community. Forever.
              </p>

              {/* Submit tweet URL */}
              <div className="flex flex-col sm:flex-row gap-3 max-w-lg mx-auto">
                <div className="relative flex-1">
                  <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
                  <Input
                    value={tweetUrl}
                    onChange={(e) => setTweetUrl(e.target.value)}
                    placeholder="Paste tweet URL to tokenize..."
                    className="pl-10 bg-card/60 border-border/50 h-11"
                  />
                </div>
                <Button className="btn-gradient-green h-11 px-6 font-bold shrink-0">
                  <Flame className="w-4 h-4 mr-2" />
                  Tokenize Tweet
                </Button>
              </div>
            </motion.div>
          </div>
        </section>

        {/* Stats bar */}
        <motion.section
          initial={{ opacity: 0, y: 12, filter: "blur(4px)" }}
          animate={{ opacity: 1, y: 0, filter: "blur(0px)" }}
          transition={{ duration: 0.6, ease, delay: 0.15 }}
          className="px-4 -mt-4 mb-16"
        >
          <div className="max-w-4xl mx-auto grid grid-cols-2 sm:grid-cols-4 gap-3">
            {[
              { label: "Tweets Tokenized", value: "1,247" },
              { label: "Total Fees Earned", value: "8,432 SOL" },
              { label: "Eligible Commenters", value: "47.2K" },
              { label: "Avg. Fee/Tweet", value: "6.76 SOL" },
            ].map((stat, i) => (
              <Card key={i} className="bg-card/40 border-border/30 backdrop-blur-sm">
                <CardContent className="p-4 text-center">
                  <div className="text-xl font-bold text-foreground tabular-nums">{stat.value}</div>
                  <div className="text-xs text-muted-foreground mt-0.5">{stat.label}</div>
                </CardContent>
              </Card>
            ))}
          </div>
        </motion.section>

        {/* How it works */}
        <section className="px-4 mb-20">
          <div className="max-w-4xl mx-auto">
            <motion.div
              initial={{ opacity: 0, y: 14, filter: "blur(4px)" }}
              whileInView={{ opacity: 1, y: 0, filter: "blur(0px)" }}
              viewport={{ once: true, amount: 0.2 }}
              transition={{ duration: 0.6, ease }}
            >
              <h2 className="text-2xl font-bold text-foreground mb-2 text-center">How Meteorite Works</h2>
              <p className="text-muted-foreground text-center mb-10 text-sm">From viral tweet to revenue machine in 5 steps</p>
            </motion.div>

            <div className="space-y-4">
              {HOW_IT_WORKS.map((item, i) => (
                <motion.div
                  key={i}
                  initial={{ opacity: 0, x: i % 2 === 0 ? -16 : 16, filter: "blur(4px)" }}
                  whileInView={{ opacity: 1, x: 0, filter: "blur(0px)" }}
                  viewport={{ once: true, amount: 0.2 }}
                  transition={{ duration: 0.5, ease, delay: i * 0.08 }}
                >
                  <Card className="bg-card/40 border-border/30 hover:border-orange-500/20 transition-colors duration-300">
                    <CardContent className="p-5 flex items-start gap-4">
                      <div className="flex-shrink-0 w-10 h-10 rounded-lg bg-orange-500/10 border border-orange-500/20 flex items-center justify-center">
                        <span className="text-orange-400 font-black text-sm">{item.step}</span>
                      </div>
                      <div>
                        <h3 className="font-bold text-foreground text-sm mb-1">{item.title}</h3>
                        <p className="text-muted-foreground text-sm leading-relaxed">{item.desc}</p>
                      </div>
                    </CardContent>
                  </Card>
                </motion.div>
              ))}
            </div>
          </div>
        </section>

        {/* Features grid */}
        <section className="px-4 mb-20">
          <div className="max-w-4xl mx-auto">
            <motion.div
              initial={{ opacity: 0, y: 14, filter: "blur(4px)" }}
              whileInView={{ opacity: 1, y: 0, filter: "blur(0px)" }}
              viewport={{ once: true, amount: 0.2 }}
              transition={{ duration: 0.6, ease }}
            >
              <h2 className="text-2xl font-bold text-foreground mb-8 text-center">Why Meteorite Changes Everything</h2>
            </motion.div>

            <div className="grid sm:grid-cols-2 gap-4">
              {FEATURES.map((feat, i) => (
                <motion.div
                  key={i}
                  initial={{ opacity: 0, y: 16, filter: "blur(4px)" }}
                  whileInView={{ opacity: 1, y: 0, filter: "blur(0px)" }}
                  viewport={{ once: true, amount: 0.2 }}
                  transition={{ duration: 0.5, ease, delay: i * 0.08 }}
                >
                  <Card className="bg-card/40 border-border/30 h-full hover:border-orange-500/20 transition-colors duration-300">
                    <CardContent className="p-6">
                      <div className="w-10 h-10 rounded-lg bg-orange-500/10 border border-orange-500/20 flex items-center justify-center mb-4">
                        <feat.icon className="w-5 h-5 text-orange-400" />
                      </div>
                      <h3 className="font-bold text-foreground mb-2">{feat.title}</h3>
                      <p className="text-muted-foreground text-sm leading-relaxed">{feat.desc}</p>
                    </CardContent>
                  </Card>
                </motion.div>
              ))}
            </div>
          </div>
        </section>

        {/* Fee breakdown */}
        <section className="px-4 mb-20">
          <div className="max-w-2xl mx-auto">
            <motion.div
              initial={{ opacity: 0, y: 14, filter: "blur(4px)" }}
              whileInView={{ opacity: 1, y: 0, filter: "blur(0px)" }}
              viewport={{ once: true, amount: 0.2 }}
              transition={{ duration: 0.6, ease }}
            >
              <Card className="bg-card/40 border-border/30 overflow-hidden">
                <div className="bg-orange-500/5 border-b border-orange-500/10 px-6 py-4">
                  <h3 className="font-bold text-foreground flex items-center gap-2">
                    <TrendingUp className="w-4 h-4 text-orange-400" />
                    Fee Distribution Breakdown
                  </h3>
                </div>
                <CardContent className="p-6">
                  <div className="space-y-4">
                    <div className="flex items-center justify-between">
                      <span className="text-sm text-muted-foreground">Swap Fee</span>
                      <span className="font-bold text-foreground">2%</span>
                    </div>
                    <Separator className="bg-border/30" />
                    <div className="flex items-center justify-between">
                      <span className="text-sm text-muted-foreground">Tweet Owner Share</span>
                      <span className="font-bold text-orange-400">25% of fees</span>
                    </div>
                    <div className="flex items-center justify-between">
                      <span className="text-sm text-muted-foreground">Commenters Share (split equally)</span>
                      <span className="font-bold text-amber-400">25% of fees</span>
                    </div>
                    <div className="flex items-center justify-between">
                      <span className="text-sm text-muted-foreground">{BRAND.name} Platform</span>
                      <span className="font-bold text-foreground">50% of fees</span>
                    </div>
                    <Separator className="bg-border/30" />
                    <div className="text-xs text-muted-foreground leading-relaxed">
                      Example: A tokenized tweet generates $10,000 in volume → $200 in fees → $50 to tweet owner, $50 split among commenters, $100 to platform.
                    </div>
                  </div>
                </CardContent>
              </Card>
            </motion.div>
          </div>
        </section>

        {/* Rules */}
        <section className="px-4 mb-20">
          <div className="max-w-3xl mx-auto">
            <motion.div
              initial={{ opacity: 0, y: 14, filter: "blur(4px)" }}
              whileInView={{ opacity: 1, y: 0, filter: "blur(0px)" }}
              viewport={{ once: true, amount: 0.2 }}
              transition={{ duration: 0.6, ease }}
            >
              <h2 className="text-2xl font-bold text-foreground mb-2 text-center">Eligibility Rules</h2>
              <p className="text-muted-foreground text-center mb-8 text-sm">Quality over quantity. Only real people earn.</p>
            </motion.div>

            <div className="grid sm:grid-cols-2 gap-3">
              {RULES.map((rule, i) => (
                <motion.div
                  key={i}
                  initial={{ opacity: 0, y: 12, filter: "blur(4px)" }}
                  whileInView={{ opacity: 1, y: 0, filter: "blur(0px)" }}
                  viewport={{ once: true, amount: 0.2 }}
                  transition={{ duration: 0.5, ease, delay: i * 0.06 }}
                  className={`flex items-center gap-3 px-4 py-3 rounded-lg border ${
                    rule.ok
                      ? "bg-green-500/5 border-green-500/15"
                      : "bg-red-500/5 border-red-500/15"
                  }`}
                >
                  <rule.icon className={`w-4 h-4 flex-shrink-0 ${rule.ok ? "text-green-400" : "text-red-400"}`} />
                  <span className="text-sm text-foreground">{rule.text}</span>
                </motion.div>
              ))}
            </div>
          </div>
        </section>

        {/* Live tokenized tweets */}
        <section className="px-4 mb-20">
          <div className="max-w-4xl mx-auto">
            <motion.div
              initial={{ opacity: 0, y: 14, filter: "blur(4px)" }}
              whileInView={{ opacity: 1, y: 0, filter: "blur(0px)" }}
              viewport={{ once: true, amount: 0.2 }}
              transition={{ duration: 0.6, ease }}
            >
              <h2 className="text-2xl font-bold text-foreground mb-2 text-center">Live Tokenized Tweets</h2>
              <p className="text-muted-foreground text-center mb-8 text-sm">Recently tokenized tweets generating fees right now</p>
            </motion.div>

            <div className="space-y-3">
              {MOCK_TOKENIZED_TWEETS.map((tweet, i) => (
                <motion.div
                  key={tweet.id}
                  initial={{ opacity: 0, y: 12, filter: "blur(4px)" }}
                  whileInView={{ opacity: 1, y: 0, filter: "blur(0px)" }}
                  viewport={{ once: true, amount: 0.2 }}
                  transition={{ duration: 0.5, ease, delay: i * 0.08 }}
                >
                  <Card className="bg-card/40 border-border/30 hover:border-border/50 transition-colors duration-300">
                    <CardContent className="p-5">
                      <div className="flex items-start justify-between gap-4 mb-3">
                        <div className="flex items-center gap-2">
                          <div className="w-8 h-8 rounded-full bg-muted flex items-center justify-center text-xs font-bold text-muted-foreground">
                            {tweet.author[1]?.toUpperCase()}
                          </div>
                          <div>
                            <div className="flex items-center gap-1.5">
                              <span className="font-bold text-foreground text-sm">{tweet.author}</span>
                              <BadgeCheck className="w-3.5 h-3.5 text-blue-400" />
                            </div>
                            <span className="text-xs text-muted-foreground">{tweet.createdAt}</span>
                          </div>
                        </div>
                        <Badge
                          variant="outline"
                          className={`text-[10px] uppercase tracking-wider font-semibold ${
                            tweet.status === "live"
                              ? "border-green-500/30 text-green-400 bg-green-500/5"
                              : "border-yellow-500/30 text-yellow-400 bg-yellow-500/5"
                          }`}
                        >
                          {tweet.status}
                        </Badge>
                      </div>

                      <p className="text-sm text-foreground/80 mb-4 leading-relaxed">{tweet.content}</p>

                      <div className="flex items-center gap-4 text-xs text-muted-foreground">
                        <span className="flex items-center gap-1">
                          <MessageSquare className="w-3 h-3" />
                          {tweet.totalCommenters} comments
                        </span>
                        <span className="flex items-center gap-1">
                          <CheckCircle2 className="w-3 h-3 text-green-400" />
                          {tweet.eligibleCommenters} eligible
                        </span>
                        <span className="flex items-center gap-1">
                          <DollarSign className="w-3 h-3 text-orange-400" />
                          {tweet.totalFeesEarned} SOL earned
                        </span>
                        {tweet.tokenCA && (
                          <span className="ml-auto font-mono text-[10px] text-muted-foreground/60 truncate max-w-[120px]">
                            {tweet.tokenCA}
                          </span>
                        )}
                      </div>
                    </CardContent>
                  </Card>
                </motion.div>
              ))}
            </div>
          </div>
        </section>

        {/* CTA */}
        <section className="px-4">
          <motion.div
            initial={{ opacity: 0, y: 14, filter: "blur(4px)" }}
            whileInView={{ opacity: 1, y: 0, filter: "blur(0px)" }}
            viewport={{ once: true, amount: 0.2 }}
            transition={{ duration: 0.6, ease }}
            className="max-w-2xl mx-auto text-center"
          >
            <Card className="bg-gradient-to-b from-orange-500/10 to-transparent border-orange-500/20">
              <CardContent className="p-8 sm:p-12">
                <Flame className="w-10 h-10 text-orange-400 mx-auto mb-4" />
                <h2 className="text-2xl font-bold text-foreground mb-3">Ready to Monetize the Timeline?</h2>
                <p className="text-muted-foreground text-sm mb-6 max-w-md mx-auto" style={{ textWrap: "balance" }}>
                  Comment on viral tweets. Get verified. Earn from every trade. 
                  This is the most hyped thing on the internet.
                </p>
                <Button className="btn-gradient-green h-11 px-8 font-bold">
                  <Flame className="w-4 h-4 mr-2" />
                  Start Earning from Tweets
                </Button>
              </CardContent>
            </Card>
          </motion.div>
        </section>
      </div>
    </LaunchpadLayout>
  );
}
