import { useState, useEffect, useCallback } from "react";
import { motion } from "framer-motion";
import { Flame, Shield, DollarSign, Users, CheckCircle2, XCircle, Zap, TrendingUp, MessageSquare, BadgeCheck, Search, ExternalLink, Copy, Loader2, Heart, Repeat2, MessageCircle } from "lucide-react";
import { MeteoriteTokenDetail } from "@/components/meteorite/MeteoriteTokenDetail";
import { XIcon } from "@/components/icons/XIcon";
import { LaunchpadLayout } from "@/components/layout/LaunchpadLayout";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { BRAND } from "@/config/branding";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";

interface TweetPreview {
  author: string;
  authorName: string;
  authorAvatar: string;
  content: string;
  createdAt: string;
  likes: number;
  retweets: number;
  replies: number;
  isVerified: boolean;
  verifiedType: string;
}

const ease = [0.16, 1, 0.3, 1] as [number, number, number, number];

type TokenizationStep = "idle" | "submitting" | "pending_payment" | "checking_payment" | "generating" | "launching" | "success" | "error";

interface MeteoriteToken {
  id: string;
  tweet_url: string;
  tweet_author: string | null;
  tweet_content: string | null;
  token_name: string | null;
  token_ticker: string | null;
  mint_address: string | null;
  pumpfun_url: string | null;
  image_url: string | null;
  status: string;
  total_fees_earned: number;
  created_at: string;
}

const FEATURES = [
  { icon: Flame, title: "Tweet Goes Viral → Token Gets Born", desc: "Any tweet can be turned into a tradeable token. The more engagement, the more valuable it becomes." },
  { icon: DollarSign, title: "25% to Tweet Owner", desc: "The original tweet author receives 25% of all swap fees generated by their tokenized tweet." },
  { icon: Users, title: "25% Split Among Commenters", desc: "Every verified commenter splits 25% of swap fees proportionally. Quality over quantity." },
  { icon: Shield, title: "Blue Check Required", desc: "Only verified X accounts can participate. No bots, no spam, no shadowbanned accounts." },
];

const HOW_IT_WORKS = [
  { step: "01", title: "Submit Tweet URL", desc: "Paste a tweet URL you want to tokenize. Pay 0.1 SOL launch fee." },
  { step: "02", title: "AI Generates Meme", desc: "Our AI creates a unique meme character based on the tweet's content." },
  { step: "03", title: "Token Launches on Pump.fun", desc: "The token launches with the tweet as the official X link." },
  { step: "04", title: "Trade & Earn", desc: "Every swap generates fees. 25% to the author, 25% to commenters. Forever." },
];

const RULES = [
  { icon: BadgeCheck, text: "Must have X Blue verification (checkmark)", ok: true },
  { icon: Shield, text: "Account must NOT be shadowbanned", ok: true },
  { icon: MessageSquare, text: "Only 1 comment per tweet counts", ok: true },
  { icon: DollarSign, text: "25% fees → tweet owner", ok: true },
  { icon: Users, text: "25% fees → split among all eligible commenters", ok: true },
  { icon: Zap, text: "2% swap fee on every trade", ok: true },
  { icon: XCircle, text: "No duplicate comments from same account", ok: false },
  { icon: XCircle, text: "No shadowbanned or suspended accounts", ok: false },
  { icon: XCircle, text: "No bot accounts or automated replies", ok: false },
];

function formatCount(n: number): string {
  if (n >= 1_000_000) return (n / 1_000_000).toFixed(1) + "M";
  if (n >= 1_000) return (n / 1_000).toFixed(1) + "K";
  return String(n);
}

function TweetCard({ tweet, tweetUrl }: { tweet: TweetPreview; tweetUrl: string }) {
  const tweetDate = tweet.createdAt ? new Date(tweet.createdAt) : null;
  const formattedDate = tweetDate
    ? tweetDate.toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" })
    : null;

  return (
    <div className="max-w-md mx-auto rounded-2xl border border-border/50 bg-card/80 backdrop-blur-sm overflow-hidden">
      <div className="p-4">
        {/* Author row */}
        <div className="flex items-start justify-between mb-3">
          <div className="flex items-center gap-3">
            <Avatar className="h-11 w-11">
              <AvatarImage src={tweet.authorAvatar} />
              <AvatarFallback className="text-sm bg-muted font-bold">
                {tweet.authorName?.slice(0, 2) || "?"}
              </AvatarFallback>
            </Avatar>
            <div className="min-w-0">
              <div className="flex items-center gap-1">
                <span className="font-bold text-foreground text-[15px] truncate">{tweet.authorName}</span>
                {tweet.isVerified && (
                  <BadgeCheck className={`w-[18px] h-[18px] shrink-0 fill-current ${
                    tweet.verifiedType === "gold" ? "text-badge-gold" : "text-badge-blue"
                  }`} />
                )}
              </div>
              <span className="text-[13px] text-muted-foreground">@{tweet.author}</span>
            </div>
          </div>
          <XIcon className="w-5 h-5 text-foreground/60 shrink-0 mt-1" />
        </div>

        {/* Content */}
        <p className="text-[15px] text-foreground leading-[1.4] whitespace-pre-wrap mb-3">
          {tweet.content}
        </p>

        {/* Date */}
        {formattedDate && (
          <p className="text-[13px] text-muted-foreground mb-3">{formattedDate}</p>
        )}

        {/* Engagement stats */}
        <div className="flex items-center gap-6 pt-3 border-t border-border/30">
          <span className="flex items-center gap-1.5 text-[13px] text-muted-foreground">
            <MessageCircle className="w-4 h-4" />
            {formatCount(tweet.replies)}
          </span>
          <span className="flex items-center gap-1.5 text-[13px] text-muted-foreground">
            <Repeat2 className="w-4 h-4" />
            {formatCount(tweet.retweets)}
          </span>
          <span className="flex items-center gap-1.5 text-[13px] text-muted-foreground">
            <Heart className="w-4 h-4" />
            {formatCount(tweet.likes)}
          </span>
        </div>
      </div>
    </div>
  );
}

export default function MeteoritePage() {
  const [tweetUrl, setTweetUrl] = useState("");
  const [step, setStep] = useState<TokenizationStep>("idle");
  const [currentTokenId, setCurrentTokenId] = useState<string | null>(null);
  const [devWalletAddress, setDevWalletAddress] = useState<string | null>(null);
  const [tweetPreview, setTweetPreview] = useState<TweetPreview | null>(null);
  const [launchResult, setLaunchResult] = useState<{ tokenName: string; tokenTicker: string; mintAddress: string; pumpfunUrl: string } | null>(null);
  const [errorMsg, setErrorMsg] = useState("");

  // Live tokens from DB
  const [liveTokens, setLiveTokens] = useState<MeteoriteToken[]>([]);
  const [stats, setStats] = useState({ totalTokens: 0, totalLive: 0, totalFees: 0 });
  const [selectedToken, setSelectedToken] = useState<MeteoriteToken | null>(null);
  const [detailOpen, setDetailOpen] = useState(false);

  // Fetch live tokens
  useEffect(() => {
    const fetchTokens = async () => {
      const { data } = await supabase
        .from("meteorite_tokens" as any)
        .select("id, tweet_url, tweet_author, tweet_content, token_name, token_ticker, mint_address, pumpfun_url, image_url, status, total_fees_earned, created_at")
        .order("created_at", { ascending: false })
        .limit(20);

      if (data) {
        const tokens = data as unknown as MeteoriteToken[];
        setLiveTokens(tokens);
        setStats({
          totalTokens: tokens.length,
          totalLive: tokens.filter(t => t.status === "live").length,
          totalFees: tokens.reduce((sum, t) => sum + (Number(t.total_fees_earned) || 0), 0),
        });
      }
    };
    fetchTokens();
  }, [launchResult]);

  // Submit tweet for tokenization
  const handleSubmit = async () => {
    if (!tweetUrl.includes("x.com") && !tweetUrl.includes("twitter.com")) {
      toast.error("Please enter a valid X/Twitter URL");
      return;
    }
    setStep("submitting");
    setErrorMsg("");
    setTweetPreview(null);
    try {
      const projectId = import.meta.env.VITE_SUPABASE_PROJECT_ID;
      const res = await fetch(`https://${projectId}.supabase.co/functions/v1/meteorite-init`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ tweetUrl }),
      });
      const data = await res.json();
      if (data.error) throw new Error(data.error);

      // Store tweet preview if returned
      if (data.tweetData) {
        setTweetPreview(data.tweetData as TweetPreview);
      }

      if (data.alreadyExists && data.status !== "failed") {
        setCurrentTokenId(data.id);
        setDevWalletAddress(data.devWalletAddress);
        if (data.status === "pending_payment") {
          setStep("pending_payment");
        } else {
          toast.info("This tweet is already being processed");
          setStep("idle");
        }
        return;
      }

      setCurrentTokenId(data.id);
      setDevWalletAddress(data.devWalletAddress);
      setStep("pending_payment");
      toast.success("Tweet loaded! Send 0.1 SOL to launch.");
    } catch (e: any) {
      setErrorMsg(e.message);
      setStep("error");
    }
  };

  // Poll for payment confirmation
  const checkPayment = useCallback(async () => {
    if (!currentTokenId) return;
    setStep("checking_payment");
    try {
      const projectId = import.meta.env.VITE_SUPABASE_PROJECT_ID;
      const res = await fetch(`https://${projectId}.supabase.co/functions/v1/meteorite-confirm`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ tokenId: currentTokenId }),
      });
      const data = await res.json();
      if (data.error) throw new Error(data.error);

      if (data.confirmed) {
        toast.success("Payment confirmed! Generating meme...");
        setStep("generating");
        triggerLaunch();
      } else {
        toast.info(`Balance: ${data.balance?.toFixed(4) || 0} SOL — need 0.1 SOL`);
        setStep("pending_payment");
      }
    } catch (e: any) {
      toast.error(e.message);
      setStep("pending_payment");
    }
  }, [currentTokenId]);

  // Trigger the launch
  const triggerLaunch = async () => {
    if (!currentTokenId) return;
    setStep("launching");
    try {
      const projectId = import.meta.env.VITE_SUPABASE_PROJECT_ID;
      const res = await fetch(`https://${projectId}.supabase.co/functions/v1/meteorite-launch`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ tokenId: currentTokenId }),
      });
      const data = await res.json();
      if (data.error) throw new Error(data.error);

      setLaunchResult({
        tokenName: data.tokenName,
        tokenTicker: data.tokenTicker,
        mintAddress: data.mintAddress,
        pumpfunUrl: data.pumpfunUrl,
      });
      setStep("success");
      toast.success(`🚀 ${data.tokenName} ($${data.tokenTicker}) launched!`);
    } catch (e: any) {
      setErrorMsg(e.message);
      setStep("error");
    }
  };

  const copyToClipboard = (text: string) => {
    navigator.clipboard.writeText(text);
    toast.success("Copied!");
  };

  const resetFlow = () => {
    setStep("idle");
    setTweetUrl("");
    setCurrentTokenId(null);
    setDevWalletAddress(null);
    setLaunchResult(null);
    setTweetPreview(null);
    setErrorMsg("");
  };

  const timeAgo = (dateStr: string) => {
    const diff = Date.now() - new Date(dateStr).getTime();
    const mins = Math.floor(diff / 60000);
    if (mins < 60) return `${mins}m ago`;
    const hrs = Math.floor(mins / 60);
    if (hrs < 24) return `${hrs}h ago`;
    return `${Math.floor(hrs / 24)}d ago`;
  };

  return (
    <LaunchpadLayout>
      <div className="min-h-screen pb-24">
        {/* Hero */}
        <section className="relative overflow-hidden pt-16 pb-20 px-4">
          <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_top,hsl(var(--primary)/0.08)_0%,transparent_60%)]" />
          <div className="max-w-4xl mx-auto relative z-10">
            <motion.div initial={{ opacity: 0, y: 18, filter: "blur(4px)" }} animate={{ opacity: 1, y: 0, filter: "blur(0px)" }} transition={{ duration: 0.7, ease }} className="text-center">
              <Badge variant="outline" className="mb-6 border-orange-500/40 text-orange-400 bg-orange-500/5 px-3 py-1 text-xs font-semibold tracking-wide uppercase">
                <Flame className="w-3 h-3 mr-1.5" />
                Meteorite Mode
              </Badge>
              <h1 className="text-4xl sm:text-5xl lg:text-6xl font-black text-foreground leading-[0.95] tracking-tight mb-6">
                Every Tweet is a<br />
                <span className="text-transparent bg-clip-text bg-gradient-to-r from-orange-400 via-amber-400 to-yellow-300">Cash Machine</span>
              </h1>
              <p className="text-muted-foreground text-lg sm:text-xl max-w-2xl mx-auto leading-relaxed mb-10" style={{ textWrap: "balance" }}>
                Tweets get tokenized. Tweet owners earn 25%. Commenters split 25%.
                Every trade generates fees that flow to creators and their community. Forever.
              </p>

              {/* Tokenization Flow */}
              {step === "idle" && (
                <div className="flex flex-col sm:flex-row gap-3 max-w-lg mx-auto">
                  <div className="relative flex-1">
                    <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
                    <Input value={tweetUrl} onChange={(e) => setTweetUrl(e.target.value)} placeholder="Paste tweet URL to tokenize..." className="pl-10 bg-card/60 border-border/50 h-11" onKeyDown={(e) => e.key === "Enter" && handleSubmit()} />
                  </div>
                  <Button onClick={handleSubmit} className="btn-gradient-green h-11 px-6 font-bold shrink-0">
                    <Flame className="w-4 h-4 mr-2" />
                    Tokenize Tweet
                  </Button>
                </div>
              )}

              {step === "submitting" && (
                <div className="flex flex-col items-center gap-3 text-muted-foreground">
                  <Loader2 className="w-5 h-5 animate-spin" />
                  <span>Loading tweet...</span>
                </div>
              )}

              {/* Payment step with tweet preview */}
              {(step === "pending_payment" || step === "checking_payment") && devWalletAddress && (
                <div className="space-y-4">
                  {/* Tweet preview */}
                  {tweetPreview && (
                    <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.4, ease }}>
                      <TweetCard tweet={tweetPreview} tweetUrl={tweetUrl} />
                    </motion.div>
                  )}

                  <Card className="max-w-md mx-auto bg-card/60 border-orange-500/30">
                    <CardContent className="p-6 text-center space-y-4">
                      <div className="text-sm font-semibold text-foreground">Send 0.1 SOL to launch this token</div>
                      <div className="bg-background/60 rounded-lg p-4 border border-border/50">
                        <div className="text-xs text-muted-foreground mb-1">Dev Wallet Address</div>
                        <div className="font-mono text-xs text-foreground break-all">{devWalletAddress}</div>
                      </div>
                      <Button size="sm" variant="outline" onClick={() => copyToClipboard(devWalletAddress)} className="text-xs">
                        <Copy className="w-3 h-3 mr-1.5" /> Copy Address
                      </Button>
                      <Separator className="bg-border/30" />
                      <Button onClick={checkPayment} disabled={step === "checking_payment"} className="w-full btn-gradient-green">
                        {step === "checking_payment" ? <><Loader2 className="w-4 h-4 mr-2 animate-spin" /> Checking...</> : <><CheckCircle2 className="w-4 h-4 mr-2" /> I've Sent 0.1 SOL</>}
                      </Button>
                      <button onClick={resetFlow} className="text-xs text-muted-foreground hover:text-foreground transition-colors">Cancel</button>
                    </CardContent>
                  </Card>
                </div>
              )}

              {/* Generating / Launching with tweet preview */}
              {(step === "generating" || step === "launching") && (
                <div className="space-y-4">
                  {tweetPreview && (
                    <div className="opacity-60">
                      <TweetCard tweet={tweetPreview} tweetUrl={tweetUrl} />
                    </div>
                  )}
                  <Card className="max-w-md mx-auto bg-card/60 border-orange-500/30">
                    <CardContent className="p-8 text-center space-y-4">
                      <Loader2 className="w-8 h-8 animate-spin text-orange-400 mx-auto" />
                      <div className="text-sm font-semibold text-foreground">
                        {step === "generating" ? "AI is generating your meme..." : "Launching token on pump.fun..."}
                      </div>
                      <p className="text-xs text-muted-foreground">This may take 30-60 seconds</p>
                    </CardContent>
                  </Card>
                </div>
              )}

              {step === "success" && launchResult && (
                <Card className="max-w-md mx-auto bg-card/60 border-green-500/30">
                  <CardContent className="p-6 text-center space-y-4">
                    <CheckCircle2 className="w-10 h-10 text-green-400 mx-auto" />
                    <div className="text-lg font-bold text-foreground">{launchResult.tokenName} (${launchResult.tokenTicker})</div>
                    <div className="bg-background/60 rounded-lg p-3 border border-border/50">
                      <div className="text-xs text-muted-foreground mb-1">Contract Address</div>
                      <div className="font-mono text-xs text-foreground break-all">{launchResult.mintAddress}</div>
                    </div>
                    <div className="flex gap-2 justify-center">
                      <Button size="sm" variant="outline" onClick={() => copyToClipboard(launchResult.mintAddress)}>
                        <Copy className="w-3 h-3 mr-1.5" /> Copy CA
                      </Button>
                      <a href={launchResult.pumpfunUrl} target="_blank" rel="noopener noreferrer">
                        <Button size="sm" className="btn-gradient-green">
                          <ExternalLink className="w-3 h-3 mr-1.5" /> View on Pump.fun
                        </Button>
                      </a>
                    </div>
                    <button onClick={resetFlow} className="text-xs text-muted-foreground hover:text-foreground transition-colors">Tokenize Another Tweet</button>
                  </CardContent>
                </Card>
              )}

              {step === "error" && (
                <Card className="max-w-md mx-auto bg-card/60 border-red-500/30">
                  <CardContent className="p-6 text-center space-y-3">
                    <XCircle className="w-8 h-8 text-red-400 mx-auto" />
                    <div className="text-sm font-semibold text-foreground">Something went wrong</div>
                    <p className="text-xs text-red-400">{errorMsg}</p>
                    <Button onClick={resetFlow} variant="outline" size="sm">Try Again</Button>
                  </CardContent>
                </Card>
              )}
            </motion.div>
          </div>
        </section>

        {/* Stats bar - real data */}
        <motion.section initial={{ opacity: 0, y: 12, filter: "blur(4px)" }} animate={{ opacity: 1, y: 0, filter: "blur(0px)" }} transition={{ duration: 0.6, ease, delay: 0.15 }} className="px-4 -mt-4 mb-16">
          <div className="max-w-4xl mx-auto grid grid-cols-2 sm:grid-cols-3 gap-3">
            {[
              { label: "Tweets Tokenized", value: stats.totalTokens.toLocaleString() },
              { label: "Live Tokens", value: stats.totalLive.toLocaleString() },
              { label: "Total Fees Earned", value: `${stats.totalFees.toFixed(2)} SOL` },
            ].map((stat, i) => (
              <Card key={i} className="bg-card/40 border-border/30 backdrop-blur-sm">
                <CardContent className="p-4 text-center">
                  <div className="text-xl font-bold text-foreground tabular-nums">{stat.value}</div>
                  <div className="text-xs text-muted-foreground mt-0.5">{stat.label}</div>
                </CardContent>
              </Card>
            ))}
          </div>
        </motion.section>

        {/* How it works */}
        <section className="px-4 mb-20">
          <div className="max-w-4xl mx-auto">
            <motion.div initial={{ opacity: 0, y: 14, filter: "blur(4px)" }} whileInView={{ opacity: 1, y: 0, filter: "blur(0px)" }} viewport={{ once: true, amount: 0.2 }} transition={{ duration: 0.6, ease }}>
              <h2 className="text-2xl font-bold text-foreground mb-2 text-center">How Meteorite Works</h2>
              <p className="text-muted-foreground text-center mb-10 text-sm">From tweet to tradeable token in 4 steps</p>
            </motion.div>
            <div className="space-y-4">
              {HOW_IT_WORKS.map((item, i) => (
                <motion.div key={i} initial={{ opacity: 0, x: i % 2 === 0 ? -16 : 16, filter: "blur(4px)" }} whileInView={{ opacity: 1, x: 0, filter: "blur(0px)" }} viewport={{ once: true, amount: 0.2 }} transition={{ duration: 0.5, ease, delay: i * 0.08 }}>
                  <Card className="bg-card/40 border-border/30 hover:border-orange-500/20 transition-colors duration-300">
                    <CardContent className="p-5 flex items-start gap-4">
                      <div className="flex-shrink-0 w-10 h-10 rounded-lg bg-orange-500/10 border border-orange-500/20 flex items-center justify-center">
                        <span className="text-orange-400 font-black text-sm">{item.step}</span>
                      </div>
                      <div>
                        <h3 className="font-bold text-foreground text-sm mb-1">{item.title}</h3>
                        <p className="text-muted-foreground text-sm leading-relaxed">{item.desc}</p>
                      </div>
                    </CardContent>
                  </Card>
                </motion.div>
              ))}
            </div>
          </div>
        </section>

        {/* Features grid */}
        <section className="px-4 mb-20">
          <div className="max-w-4xl mx-auto">
            <motion.div initial={{ opacity: 0, y: 14, filter: "blur(4px)" }} whileInView={{ opacity: 1, y: 0, filter: "blur(0px)" }} viewport={{ once: true, amount: 0.2 }} transition={{ duration: 0.6, ease }}>
              <h2 className="text-2xl font-bold text-foreground mb-8 text-center">Why Meteorite Changes Everything</h2>
            </motion.div>
            <div className="grid sm:grid-cols-2 gap-4">
              {FEATURES.map((feat, i) => (
                <motion.div key={i} initial={{ opacity: 0, y: 16, filter: "blur(4px)" }} whileInView={{ opacity: 1, y: 0, filter: "blur(0px)" }} viewport={{ once: true, amount: 0.2 }} transition={{ duration: 0.5, ease, delay: i * 0.08 }}>
                  <Card className="bg-card/40 border-border/30 h-full hover:border-orange-500/20 transition-colors duration-300">
                    <CardContent className="p-6">
                      <div className="w-10 h-10 rounded-lg bg-orange-500/10 border border-orange-500/20 flex items-center justify-center mb-4">
                        <feat.icon className="w-5 h-5 text-orange-400" />
                      </div>
                      <h3 className="font-bold text-foreground mb-2">{feat.title}</h3>
                      <p className="text-muted-foreground text-sm leading-relaxed">{feat.desc}</p>
                    </CardContent>
                  </Card>
                </motion.div>
              ))}
            </div>
          </div>
        </section>

        {/* Fee breakdown */}
        <section className="px-4 mb-20">
          <div className="max-w-2xl mx-auto">
            <motion.div initial={{ opacity: 0, y: 14, filter: "blur(4px)" }} whileInView={{ opacity: 1, y: 0, filter: "blur(0px)" }} viewport={{ once: true, amount: 0.2 }} transition={{ duration: 0.6, ease }}>
              <Card className="bg-card/40 border-border/30 overflow-hidden">
                <div className="bg-orange-500/5 border-b border-orange-500/10 px-6 py-4">
                  <h3 className="font-bold text-foreground flex items-center gap-2">
                    <TrendingUp className="w-4 h-4 text-orange-400" />
                    Fee Distribution Breakdown
                  </h3>
                </div>
                <CardContent className="p-6">
                  <div className="space-y-4">
                    <div className="flex items-center justify-between"><span className="text-sm text-muted-foreground">Swap Fee</span><span className="font-bold text-foreground">2%</span></div>
                    <Separator className="bg-border/30" />
                    <div className="flex items-center justify-between"><span className="text-sm text-muted-foreground">Tweet Owner Share</span><span className="font-bold text-orange-400">25% of fees</span></div>
                    <div className="flex items-center justify-between"><span className="text-sm text-muted-foreground">Commenters Share (split equally)</span><span className="font-bold text-amber-400">25% of fees</span></div>
                    <div className="flex items-center justify-between"><span className="text-sm text-muted-foreground">{BRAND.name} Platform</span><span className="font-bold text-foreground">50% of fees</span></div>
                    <Separator className="bg-border/30" />
                    <div className="text-xs text-muted-foreground leading-relaxed">
                      Example: A tokenized tweet generates $10,000 in volume → $200 in fees → $50 to tweet owner, $50 split among commenters, $100 to platform.
                    </div>
                  </div>
                </CardContent>
              </Card>
            </motion.div>
          </div>
        </section>

        {/* Rules */}
        <section className="px-4 mb-20">
          <div className="max-w-3xl mx-auto">
            <motion.div initial={{ opacity: 0, y: 14, filter: "blur(4px)" }} whileInView={{ opacity: 1, y: 0, filter: "blur(0px)" }} viewport={{ once: true, amount: 0.2 }} transition={{ duration: 0.6, ease }}>
              <h2 className="text-2xl font-bold text-foreground mb-2 text-center">Eligibility Rules</h2>
              <p className="text-muted-foreground text-center mb-8 text-sm">Quality over quantity. Only real people earn.</p>
            </motion.div>
            <div className="grid sm:grid-cols-2 gap-3">
              {RULES.map((rule, i) => (
                <motion.div key={i} initial={{ opacity: 0, y: 12, filter: "blur(4px)" }} whileInView={{ opacity: 1, y: 0, filter: "blur(0px)" }} viewport={{ once: true, amount: 0.2 }} transition={{ duration: 0.5, ease, delay: i * 0.06 }} className={`flex items-center gap-3 px-4 py-3 rounded-lg border ${rule.ok ? "bg-green-500/5 border-green-500/15" : "bg-red-500/5 border-red-500/15"}`}>
                  <rule.icon className={`w-4 h-4 flex-shrink-0 ${rule.ok ? "text-green-400" : "text-red-400"}`} />
                  <span className="text-sm text-foreground">{rule.text}</span>
                </motion.div>
              ))}
            </div>
          </div>
        </section>

        {/* Live tokenized tweets - REAL DATA */}
        <section className="px-4 mb-20">
          <div className="max-w-4xl mx-auto">
            <motion.div initial={{ opacity: 0, y: 14, filter: "blur(4px)" }} whileInView={{ opacity: 1, y: 0, filter: "blur(0px)" }} viewport={{ once: true, amount: 0.2 }} transition={{ duration: 0.6, ease }}>
              <h2 className="text-2xl font-bold text-foreground mb-2 text-center">Live Tokenized Tweets</h2>
              <p className="text-muted-foreground text-center mb-8 text-sm">Recently tokenized tweets generating fees right now</p>
            </motion.div>

            {liveTokens.length === 0 ? (
              <Card className="bg-card/40 border-border/30">
                <CardContent className="p-8 text-center">
                  <Flame className="w-8 h-8 text-muted-foreground/40 mx-auto mb-3" />
                  <p className="text-sm text-muted-foreground">No tweets tokenized yet. Be the first!</p>
                </CardContent>
              </Card>
            ) : (
              <div className="space-y-3">
                {liveTokens.map((token, i) => (
                  <motion.div key={token.id} initial={{ opacity: 0, y: 12, filter: "blur(4px)" }} whileInView={{ opacity: 1, y: 0, filter: "blur(0px)" }} viewport={{ once: true, amount: 0.2 }} transition={{ duration: 0.5, ease, delay: i * 0.08 }}>
                    <Card className="bg-card/40 border-border/30 hover:border-border/50 transition-colors duration-300 cursor-pointer" onClick={() => { setSelectedToken(token); setDetailOpen(true); }}>
                      <CardContent className="p-5">
                        <div className="flex items-start justify-between gap-4 mb-3">
                          <div className="flex items-center gap-2">
                            {token.image_url ? (
                              <img src={token.image_url} className="w-8 h-8 rounded-full object-cover" alt="" />
                            ) : (
                              <div className="w-8 h-8 rounded-full bg-muted flex items-center justify-center text-xs font-bold text-muted-foreground">
                                <Flame className="w-4 h-4" />
                              </div>
                            )}
                            <div>
                              <div className="flex items-center gap-1.5">
                                <span className="font-bold text-foreground text-sm">{token.token_name || "Pending..."}</span>
                                {token.token_ticker && <span className="text-xs text-muted-foreground">${token.token_ticker}</span>}
                              </div>
                              <span className="text-xs text-muted-foreground">{timeAgo(token.created_at)}</span>
                            </div>
                          </div>
                          <Badge variant="outline" className={`text-[10px] uppercase tracking-wider font-semibold ${
                            token.status === "live" ? "border-green-500/30 text-green-400 bg-green-500/5"
                            : token.status === "failed" ? "border-red-500/30 text-red-400 bg-red-500/5"
                            : "border-yellow-500/30 text-yellow-400 bg-yellow-500/5"
                          }`}>
                            {token.status}
                          </Badge>
                        </div>

                        {token.tweet_content && (
                          <p className="text-sm text-foreground/80 mb-3 leading-relaxed truncate">{token.tweet_content}</p>
                        )}

                        <div className="flex items-center gap-4 text-xs text-muted-foreground">
                          {token.total_fees_earned > 0 && (
                            <span className="flex items-center gap-1">
                              <DollarSign className="w-3 h-3 text-orange-400" />
                              {Number(token.total_fees_earned).toFixed(2)} SOL
                            </span>
                          )}
                          <a href={token.tweet_url} target="_blank" rel="noopener noreferrer" className="flex items-center gap-1 hover:text-foreground transition-colors" onClick={(e) => e.stopPropagation()}>
                            <ExternalLink className="w-3 h-3" /> Tweet
                          </a>
                          {token.pumpfun_url && (
                            <a href={token.pumpfun_url} target="_blank" rel="noopener noreferrer" className="flex items-center gap-1 hover:text-foreground transition-colors" onClick={(e) => e.stopPropagation()}>
                              <ExternalLink className="w-3 h-3" /> Pump.fun
                            </a>
                          )}
                          {token.mint_address && (
                            <button onClick={(e) => { e.stopPropagation(); copyToClipboard(token.mint_address!); }} className="ml-auto flex items-center gap-1 hover:text-foreground transition-colors">
                              <Copy className="w-3 h-3" />
                              <span className="font-mono text-[10px] truncate max-w-[100px]">{token.mint_address}</span>
                            </button>
                          )}
                        </div>
                      </CardContent>
                    </Card>
                  </motion.div>
                ))}
              </div>
            )}
          </div>
        </section>

        {/* CTA */}
        <section className="px-4">
          <motion.div initial={{ opacity: 0, y: 14, filter: "blur(4px)" }} whileInView={{ opacity: 1, y: 0, filter: "blur(0px)" }} viewport={{ once: true, amount: 0.2 }} transition={{ duration: 0.6, ease }} className="max-w-2xl mx-auto text-center">
            <Card className="bg-gradient-to-b from-orange-500/10 to-transparent border-orange-500/20">
              <CardContent className="p-8 sm:p-12">
                <Flame className="w-10 h-10 text-orange-400 mx-auto mb-4" />
                <h2 className="text-2xl font-bold text-foreground mb-3">Ready to Monetize the Timeline?</h2>
                <p className="text-muted-foreground text-sm mb-6 max-w-md mx-auto" style={{ textWrap: "balance" }}>
                  Tokenize any viral tweet. Pay 0.1 SOL. AI generates the meme. Token launches instantly.
                </p>
                <Button onClick={() => window.scrollTo({ top: 0, behavior: "smooth" })} className="btn-gradient-green h-11 px-8 font-bold">
                  <Flame className="w-4 h-4 mr-2" />
                  Tokenize a Tweet Now
                </Button>
              </CardContent>
            </Card>
          </motion.div>
        </section>
        <MeteoriteTokenDetail
          token={selectedToken}
          open={detailOpen}
          onOpenChange={setDetailOpen}
        />
      </div>
    </LaunchpadLayout>
  );
}
